version: "3"

services:

  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
#    restart: unless-stopped
    expose:
      - "9000"
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

